### ISSUE TITLE
Webhooks documentation examples not valid JSON

### ISSUE THREAD

**Issue by Thorium** [clearbank/docs#1]
https://clearbank.github.io/docs/webhooks/#payments

Invalid JSON responses in the docs, makes me wonder will the JSON be invalid in the production also, or just in the documentation.

Code examples missing commas after payload but before "Nonce":

```json
{
  "Type":"TransactionSettled",
  "Version":6,
  "Payload": {...}
  "Nonce":
}
```

Reasons arrays are missing opening square-brackets:

```json
            "Reasons":
            "Account closed"
                ]
```

...and some arrays are not closed correctly, shouldn't have comma before closing square-bracket:

```json
},
]
```

Some of the double quotation marks are copy&pastes from Word:

```json
"AccountName": “Bob Robson”,
```

**Comment by joe642** [comment]
Hi @Thorium, thank you for bringing this to our attention. We will investigate and make the appropriate changes. Joe.

**Comment by njmiddleton** [comment]
Hi @Thorium. We have reviewed your comments and have implemented changes to our documentation. Thanks for your feedback
